name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag registry.dispatch.sh/maartje/thomas-bot:$GITHUB_SHA
      - name: Build the Twitter Docker image
        run: docker build . --file Dockerfile.twitter --build-arg src=registry.dispatch.sh/maartje/thomas-bot:$GITHUB_SHA
      - name: Build the John Docker image
        run: docker build . --file Dockerfile.voice
      - name: Build the Alf Docker image
        run: docker build . --file Dockerfile.alf --tag registry.dispatch.sh/maartje/thomas-bot-alf:$GITHUB_SHA
